services:
  siteproxy:
    image: node:22
    container_name: siteproxy-node
    restart: unless-stopped
    ports:
      - "5006:5006"   # 绑定所有地址，方便 Nginx 访问
    volumes:
      - ../:/home/node/siteproxy/
    working_dir: /home/node/siteproxy/
    entrypoint: ["node","/home/node/siteproxy/bundle.cjs"]
